name: deploy
on:
  push:
    branches:
      - pandoc
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-content:
    name: build contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
        with:
          enablement: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: make build
        run: |
          make build
          touch public/.nojekyll
      - name: Test website
        uses: docker://klakegg/html-proofer:3.19.2
        with:
          entrypoint: /usr/local/bundle/bin/htmlproofer
          args: public --check-html --empty-alt-ignore --only-4xx
      - uses: actions/upload-pages-artifact@v4
        with:
          path: public

  deploy:
    name: deploy to GitHub Pages
    needs: build-content
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
